url: "https://augustinedickinson.com/Taammera-Maryam"

collections:
  miracles:
    output: true

defaults:
  -
    scope:
      type: "miracles"
    values:
      layout: "miracle"
  -
    scope:
      path: "_miracles/basil/*"
    values:
      cycle: "How Saint Basil Obtained a Miraculous Icon for the Church of the Virgin Mary"
  -
    scope:
      path: "_miracles/john/*"
    values:
      cycle: "The Vision of John"
  -
    scope:
      path: "_miracles/qwesqwam/*"
    values:
      cycle: "The Vision of Anthony of Qusqam"
  -
    scope:
      path: "_miracles/synaxary/*"
    values:
      cycle: "The Miracles of Mary from the Synaxary"
  -
    scope:
      path: "_miracles/thecla/*"
    values:
      cycle: "Thecla the Martyr"
  -
    scope:
      path: "_miracles/theophilus/*"
    values:
      cycle: "The Vision of Theophilus"